export const LIST = [
  {
    id: "123",
    shopId: "Mercadona",
    name: "Bananas",
    price: 2.5,
    quantity: 1,
    isActive: true,
  },
  {
    id: "124",
    shopId: "Mercadona",
    name: "Whole Milk",
    price: 1.2,
    quantity: 1,
    isActive: false,
  },
  {
    id: "125",
    shopId: "Mercadona",
    name: "White Bread",
    price: 1.8,
    quantity: 1,
    isActive: true,
  },
  {
    id: "126",
    shopId: "Mercadona",
    name: "Chicken Breast",
    price: 6.5,
    quantity: 1,
    isActive: false,
  },
  {
    id: "127",
    shopId: "Mercadona",
    name: "Eggs",
    price: 3.2,
    quantity: 1,
    isActive: true,
  },
  {
    id: "128",
    shopId: "Mercadona",
    name: "Pasta",
    price: 1.1,
    quantity: 1,
    isActive: true,
  },
  {
    id: "129",
    shopId: "Mercadona",
    name: "Tomato Sauce",
    price: 1.5,
    quantity: 1,
    isActive: false,
  },
  {
    id: "130",
    shopId: "Mercadona",
    name: "Olive Oil",
    price: 4.8,
    quantity: 1,
    isActive: true,
  },
  {
    id: "131",
    shopId: "Mercadona",
    name: "Coffee",
    price: 3.9,
    quantity: 1,
    isActive: false,
  },
  {
    id: "132",
    shopId: "Mercadona",
    name: "Yogurt",
    price: 2.3,
    quantity: 1,
    isActive: true,
  },
  {
    id: "133",
    shopId: "Mercadona",
    name: "Cheese",
    price: 3.7,
    quantity: 1,
    isActive: false,
  },
  {
    id: "134",
    shopId: "Mercadona",
    name: "Butter",
    price: 2.1,
    quantity: 1,
    isActive: true,
  },
  {
    id: "135",
    shopId: "Mercadona",
    name: "Orange Juice",
    price: 2.4,
    quantity: 1,
    isActive: false,
  },
  {
    id: "136",
    shopId: "Mercadona",
    name: "Cereal",
    price: 3.0,
    quantity: 1,
    isActive: true,
  },
  {
    id: "137",
    shopId: "Mercadona",
    name: "Toilet Paper",
    price: 4.2,
    quantity: 1,
    isActive: false,
  },
];

export const DAFAULT_SHOP_ID = "mercadona";
